modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"

[[mods]]
modId="moneys"
version="2.0"
displayName="Moneys!"
credits="Nah Fam This Is On Dev."
displayURL="https://mcreator.net"
authors="BulutCorbaci"
description='''
A Mod That Adds Money to The Game!
'''

[[dependencies.moneys]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




